version: '2'
services:
  hanadb:
    container_name: hanadb
    image: store/saplabs/hanaexpress:2.00.040.00.20190729.1
    restart: "unless-stopped"
    ports:
      - 39013:39013
      - 39017:39017
      - 39015:39015
      - 39041-39045:39041-39045
      - 1128-1129:1128-1129
      - 59013-59014:59013-59014
    volumes:
      - ./post_start:/hana/hooks/post_start/
      - ./dump:/hana/mounts/dump/
    environment: 
      - DUMP_FOLDER=DUMP
      - SOURCE_SCHEMA=SOURCE
      - SCHEMA_NAME=LOCALDEV
      - SCHEMA_PWD=Localdev1
    command:
      - --agree-to-sap-license
      - --dont-check-system
      - --dont-check-mount-points
      - --master-password
      - HXEHana1
  #web:
  #  container_name: nodetohana
  #  build: ./
  #  ports:
  #    - "8080:3000"
  #  depends_on:
  #    - hanadb
  #  links:
  #    - hanadb
  #  volumes:
  #    - ./:/home/app
  #  command: [ "npm", "start" ]